import { ExternalLink } from 'lucide-react';
import { arcTxUrl } from '../services/arcPayment.js';
import { formatPoints, formatTime, money, pointsFromRaw, shortAddress } from '../utils/format.js';

function pointsFromOrders(store) {
  const paidOrders = (store.orders || []).filter(order => order.paymentStatus === 'paid' || order.status === 'paid');
  const issued = paidOrders.reduce((sum, order) => sum + pointsFromRaw(order.total || 0), 0);
  const redeemed = paidOrders.reduce((sum, order) => sum + Number(order.pointsUsed || 0), 0);
  const volume = paidOrders.reduce((sum, order) => sum + Number(order.total || 0), 0);
  return { issued, redeemed, net: issued - redeemed, volume };
}

export default function PointsHistoryPage({ pointsHistory = [], stores = [], scopeLabel = 'Network Analytics' }) {
  const storeRows = stores.map(store => ({ ...store, ...pointsFromOrders(store) }));
  const totalIssued = pointsHistory.length
    ? pointsHistory.filter(row => ['earned', 'earn'].includes(row.type)).reduce((sum, row) => sum + Number(row.points || 0), 0)
    : storeRows.reduce((sum, store) => sum + store.issued, 0);
  const totalRedeemed = pointsHistory.length
    ? Math.abs(pointsHistory.filter(row => ['redeemed', 'redeem'].includes(row.type)).reduce((sum, row) => sum + Number(row.points || 0), 0))
    : storeRows.reduce((sum, store) => sum + store.redeemed, 0);
  const totalNet = totalIssued - totalRedeemed;
  const ledgerRows = pointsHistory.filter(row => !stores.length || stores.some(store => store.id === (row.store_id || row.storeId)));

  function transactionLink(txHash) {
    if (!txHash) return <span className="muted-cell">-</span>;
    return (
      <a className="explorer-link compact" href={arcTxUrl(txHash)} target="_blank" rel="noreferrer">
        {shortAddress(txHash)} <ExternalLink size={12} />
      </a>
    );
  }

  function typeBadge(type = '') {
    const normalized = type === 'earn' ? 'earned' : type === 'redeem' ? 'redeemed' : type;
    return <span className={`badge ${normalized === 'earned' ? 'ok' : 'warn'}`}>{normalized}</span>;
  }

  return (
    <section className="page-stack">
      <div className="stats-grid four">
        <article className="stat-card"><span className="green">APoint Issued</span><strong>{formatPoints(totalIssued)}</strong><small>Total points generated by paid orders</small></article>
        <article className="stat-card"><span className="orange">APoint Redeemed</span><strong>{formatPoints(totalRedeemed)}</strong><small>Used for checkout discounts</small></article>
        <article className="stat-card"><span className="blue">APoint Circulating</span><strong>{formatPoints(totalNet)}</strong><small>Issued minus redeemed</small></article>
        <article className="stat-card"><span className="green">Stores</span><strong>{stores.length}</strong><small>Participating locations</small></article>
      </div>

      <section className="panel">
        <div className="panel-head"><div><p className="eyebrow">{scopeLabel}</p><h2>APoint by Store</h2></div></div>
        <table className="data-table">
          <thead><tr><th>No.</th><th>Store</th><th>Type</th><th>APoint Issued</th><th>APoint Redeemed</th><th>Net APoint</th><th>Share</th><th>USDC Volume</th></tr></thead>
          <tbody>
            {storeRows.map((store, index) => {
              const share = totalIssued ? (store.issued / totalIssued) * 100 : 0;
              return (
                <tr key={store.id}>
                  <td>{index + 1}</td>
                  <td><strong>{store.name}</strong><br /><span className="muted-cell">{store.branch}</span></td>
                  <td>{store.type}</td>
                  <td>{formatPoints(store.issued)}</td>
                  <td>{formatPoints(store.redeemed)}</td>
                  <td><strong>{formatPoints(store.net)}</strong></td>
                  <td>
                    <div className="share-cell">
                      <span>{share.toFixed(1)}%</span>
                      <div><i style={{ width: `${Math.max(2, share)}%` }} /></div>
                    </div>
                  </td>
                  <td>{money(store.volume)}</td>
                </tr>
              );
            })}
            {!storeRows.length && <tr><td colSpan="8" className="empty-row">No store point analytics yet.</td></tr>}
          </tbody>
        </table>
      </section>

      <section className="panel full-page-panel">
        <div className="panel-head"><div><p className="eyebrow">Loyalty Ledger</p><h2>Point History</h2></div></div>
        <table className="data-table">
          <thead>
            <tr>
              <th>No.</th>
              <th>Customer Wallet</th>
              <th>Store</th>
              <th>Order / Invoice</th>
              <th>Type</th>
              <th>Points</th>
              <th>Balance After</th>
              <th>Payment Tx</th>
              <th>Proof Tx</th>
              <th>Note</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            {ledgerRows.map((row, index) => (
              <tr key={row.id}>
                <td>{index + 1}</td>
                <td>{shortAddress(row.customerWallet || row.wallet_address || '')}</td>
                <td>{row.storeName || row.store_name || '-'}</td>
                <td><strong>{row.invoiceId || row.invoice_id || row.orderId || row.order_id || '-'}</strong></td>
                <td>{typeBadge(row.type)}</td>
                <td>{formatPoints(row.points)}</td>
                <td>{formatPoints(row.balance_after ?? row.balanceAfter)}</td>
                <td>{transactionLink(row.paymentTxHash || row.payment_tx_hash || row.tx_hash)}</td>
                <td>{transactionLink(row.proofTxHash || row.proof_tx_hash)}</td>
                <td>{row.note}</td>
                <td>{formatTime(row.created_at || row.createdAt)}</td>
              </tr>
            ))}
            {!ledgerRows.length && <tr><td colSpan="11" className="empty-row">No point transactions yet.</td></tr>}
          </tbody>
        </table>
      </section>
    </section>
  );
}
