import { formatPoints, formatTime, money, pointsFromRaw, shortAddress } from '../utils/format.js';

function pointsFromOrders(store) {
  const paidOrders = (store.orders || []).filter(order => order.paymentStatus === 'paid' || order.status === 'paid');
  const issued = paidOrders.reduce((sum, order) => sum + pointsFromRaw(order.total || 0), 0);
  const redeemed = paidOrders.reduce((sum, order) => sum + Number(order.pointsUsed || 0), 0);
  const volume = paidOrders.reduce((sum, order) => sum + Number(order.total || 0), 0);
  return { issued, redeemed, net: issued - redeemed, volume };
}

export default function PointsHistoryPage({ pointsHistory = [], stores = [], scopeLabel = 'Network Analytics' }) {
  const storeRows = stores.map(store => ({ ...store, ...pointsFromOrders(store) }));
  const totalIssued = storeRows.reduce((sum, store) => sum + store.issued, 0);
  const totalRedeemed = storeRows.reduce((sum, store) => sum + store.redeemed, 0);
  const totalNet = totalIssued - totalRedeemed;

  return (
    <section className="page-stack">
      <div className="stats-grid four">
        <article className="stat-card"><span className="green">APoint Issued</span><strong>{formatPoints(totalIssued)}</strong><small>Total points generated by paid orders</small></article>
        <article className="stat-card"><span className="orange">APoint Redeemed</span><strong>{formatPoints(totalRedeemed)}</strong><small>Used for checkout discounts</small></article>
        <article className="stat-card"><span className="blue">APoint Circulating</span><strong>{formatPoints(totalNet)}</strong><small>Issued minus redeemed</small></article>
        <article className="stat-card"><span className="green">Stores</span><strong>{stores.length}</strong><small>Participating locations</small></article>
      </div>

      <section className="panel">
        <div className="panel-head"><div><p className="eyebrow">{scopeLabel}</p><h2>APoint by Store</h2></div></div>
        <table className="data-table">
          <thead><tr><th>No.</th><th>Store</th><th>Type</th><th>APoint Issued</th><th>APoint Redeemed</th><th>Net APoint</th><th>Share</th><th>USDC Volume</th></tr></thead>
          <tbody>
            {storeRows.map((store, index) => {
              const share = totalIssued ? (store.issued / totalIssued) * 100 : 0;
              return (
                <tr key={store.id}>
                  <td>{index + 1}</td>
                  <td><strong>{store.name}</strong><br /><span className="muted-cell">{store.branch}</span></td>
                  <td>{store.type}</td>
                  <td>{formatPoints(store.issued)}</td>
                  <td>{formatPoints(store.redeemed)}</td>
                  <td><strong>{formatPoints(store.net)}</strong></td>
                  <td>
                    <div className="share-cell">
                      <span>{share.toFixed(1)}%</span>
                      <div><i style={{ width: `${Math.max(2, share)}%` }} /></div>
                    </div>
                  </td>
                  <td>{money(store.volume)}</td>
                </tr>
              );
            })}
            {!storeRows.length && <tr><td colSpan="8" className="empty-row">No store point analytics yet.</td></tr>}
          </tbody>
        </table>
      </section>

      <section className="panel full-page-panel">
        <div className="panel-head"><div><p className="eyebrow">Loyalty Ledger</p><h2>Point History</h2></div></div>
        <table className="data-table">
          <thead><tr><th>No.</th><th>Customer Wallet</th><th>Type</th><th>Points</th><th>Balance After</th><th>Note</th><th>Time</th></tr></thead>
          <tbody>
            {pointsHistory.map((row, index) => (
              <tr key={row.id}>
                <td>{index + 1}</td>
                <td>{shortAddress(row.customers?.wallet_address || row.customerWallet || '')}</td>
                <td><span className={`badge ${row.type === 'earn' ? 'ok' : 'warn'}`}>{row.type}</span></td>
                <td>{formatPoints(row.points)}</td>
                <td>{formatPoints(row.balance_after ?? row.balanceAfter)}</td>
                <td>{row.note}</td>
                <td>{formatTime(row.created_at || row.createdAt)}</td>
              </tr>
            ))}
            {!pointsHistory.length && <tr><td colSpan="7" className="empty-row">No point transactions yet.</td></tr>}
          </tbody>
        </table>
      </section>
    </section>
  );
}
